name: TestPublish

on:
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'

#     - run: |
#         echo "//npm.pkg.github.com/:_authToken=${{secrets.ANDYK_PACKAGES_PAT}}" > $HOME/.npmrc
#         echo "@ironsource:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
#         cat $HOME/.npmrc

    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
